### ISSUE TITLE
Animation Call #5 (PROGRESS WALKTRHOUGH)

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/organization#15]
```meta
Date: 2021-01-26
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-01-26 17:00 UTC
```

### Agenda

PLEASE JOIN - FINALIZING STORYLINE - PREPARING FOR SCRIPT

The purpose of this meeting is to do an overall walkthrough of progress, storyline and characters. If you have not attended any of the meetings, this is a good one to join and see progress, everyone is welcome. 

If you would like to provide feedback for the animation please do so in this meeting, before we begin to create the script.

Discuss progress and show scenes:
1. Chapter 1: Storyline, characters
2. Chapter 2: Storyline, characters, btcpay features

Previous Calls for Reference:
Meetings: [0](https://github.com/btcpayserver/organization/issues/8), [1](https://github.com/btcpayserver/organization/issues/10), [2](https://github.com/btcpayserver/organization/issues/11), [3](https://github.com/btcpayserver/organization/issues/12), [4](https://github.com/btcpayserver/organization/issues/14)

### Check your timezone

https://everytimezone.com/s/d12b0b3b

### Join the call

https://meet.jit.si/BTCPayAnimationCall

### Calendar invite

(Note: Meeting change to **Tuesdays**)

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Zaxounette** [comment]
Attendees:
@britttttk , @pavlenex , @webworthy , @zaxounette

**We start by discussing Brit's script draft around multiple ideas (see here: [Script Draft V0](https://github.com/btcpayserver/btcpayserver-media/pull/14)):**
Texted bubbles for the characters might be complicated between narration timing, so we lean for emoji bubbles for the scene 1 where there are only the baker and his daughter (appartement). Not final, still to be discussed.

Emoji bubbles are approved globally for the marketplace scene for clarity, since there will be multiples characters in the scene.

**Animation-wise:**
In the first appartement scene, the idea of having the characters face their backs to the camera is exposed.
This eases the face, expression and body-language animation rendering since it's close-up.
No such problem should be expected for the marketplace scene since it's more of a global view.

**On a general note:**
Moving forward, we will focus on :
* Featuring the low or absent fees
* Payment directly to your wallet
* Invoice (simple QR code + BTCPay branding to simplify rendering)

This strips down most or all other features: 
Goal: Add simplicity, avoid confusion and increase accessibility to viewers.

Focus on fees and payments to your wallet directly + invoicing (simple QR code + branding to simplify rendering)
Striping all other features from, simplifying it and focusing on accessibility.

**Homework for next session:**
Britt and Zax: Iterate on the draft script,
Webworthy: Work on a mini-scene animation in the appartement with bubble speech tests.

Next animation call (N°6) is scheduled for Tuesday February 2nd, 1700 UTC.
