### ISSUE TITLE
Community Call #1

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#22]
```meta
Date: 2021-02-19
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-02-19 18:00 UTC
```

### Agenda

1. Discussing BTCPay Server Roadmap for 2021 https://github.com/orgs/btcpayserver/projects/9 @pavlenex @Kukks 
2. Discussing organization repo and meetings @pavlenex 
3. Design processes, progress @dstrukt 
4. BTCPay Server Animation video @Zaxounette @britttttk 
5. Forming user-testing team @britttttk 
6. Q & A, questions from community members 
7. TBD - Feel free to suggest something we can discuss.

### Check your timezone

LINK FOR TIMEZONE https://everytimezone.com/s/347a3ea6

### Join the call

LINK FOR CALL https://meet.jit.si/btcpaycommunitycall

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by dstrukt** [comment]
Happy to stick around and talk about some of the initiatives pertaining to design & the front-end stuff if that would be helpful, as we're wrapping up the wallet setup stuff in the coming weeks and will be shifting focus to new things! 

I've been meaning to take a deeper look at our roadmap on that side of things, and this would give me a good excuse to do that and vocalize my thoughts in the process / get feedback.

**Comment by Zaxounette** [comment]
Community Call N°2 notes:

BTCPay Server contributor attendees: @britttttk , @dennisreimann , @dstrukt , @pavlenex , @zaxounette, 
Call was open to all and free to join. Approximately 10 participants attended.

----

@Pavlenex presents the general roadmap for 2021. Bare in mind it's informal and can change, but gives a general idea of where the team want's to go with BTCPay Server.

To summarize, for 2021:
Q1:
* Migration from Bitpay API to in-house Greenfield API.
* Plugin infrastructure

Q2:
* Building first plugin iterations (ie. porting LN-bank from fragment to plugin)

Q3:
* Modular dashboard creation/integration

Q4
* Mobile app concepts
* Migration from "payment processor" to "payment platform".
* Improve review process
* Onboard more contributors to OSS.

For more info, click [here](https://github.com/orgs/btcpayserver/projects/9)

To keep up to date with the BTCPay Server releases, one can also go the Project milestones. For the current upcoming release, click [here](https://github.com/orgs/btcpayserver/projects/10).

---- 

@pavlenex : 
Github discussions have also been implemented for the BTCPay Server repository, for people that prefer old-style forum-like discussions. See [here](https://github.com/btcpayserver/btcpayserver/discussions).
The current workflow is the following:
* If you have a bug, you can report it by starting a new discussion.
* If you have a feature request, you can also start a discussion regarding it.
Voting is enabled on discussions, and feature requests may be prioritized based on votes by the community.

Github issues are therefor considered a TODO list for confirmed bugs & validated feature requests that have been submitted as a discussion.

---- 
@pavlenex :
Organization repo for all BTCPay server calls.
BTCPay Server has an Organization repository, where all team calls are scheduled.
You can access it [here](https://github.com/btcpayserver/organization).
Click on an issue to view the details (date, time, agenda, timezone sync, call link, etc ...)

Call are open for anyone.
Want to give feedback on a documentation call ? Hop in ! 
Need guidance on how to start contributing designs ? Join us !

----


@dstrukt + @dennisreimann  : 
Design in BTCPay Server:
Designing upcoming features and improving on the current UI/UX is always in need of more eyes.
For those who wish to see what is being worked on, and provide feedback, you can go to the BTCPay Server Figma page [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY).
If you wish to contribute designs to BTCPay Server, a design guideline has been established by the community. You can consult it [here](https://design.btcpayserver.org/).

The general focus at the time being in the design process is improving the UX.
ie. how easy it is to set up a wallet. Including that in the upcoming dashboard.

@dstrukt Explains design feedback and workflow. 
Secondary goals:
* Improve design workflow process.
* Improve design documentation in Q2 (documentation in Figma).

Aditionnal note: Contributing with designs following the design guidelines is easier for @dstrukt and @dennisreimann to work with.

---- 

@britttttk + @zaxounette :
BTCPay Server Animation video N°2:
**SPOILER ALERT !**
Sneak peak at some pre-animation renders.
Animation should in time replace the actual animation on the btcpayserver.org website
Short explanation of the goal, storyboard.

Preview, workflow, sketches and current renders can be seen [here](https://app.milanote.com/1KEd1q1fovn698/btcpay-animated-video?p=nZfM3RpnrSC)

----

@britttttk 
Forming a user testing team (very soon):
Anyone can participate, no technical knowledge required.

BTCPay Server will be deploying an in-house testing BTCPay Server instance.
Users will be able to join that instance, and test out the upcoming features. The goal being to have more eyes on upcoming releases ad get more feedback and bug reports before release, instead of having to patch bugs after release.

Want to become a tester ? Hit us in the [chat](https://chat.btcpayserver.org) !


----

Question: Will plugins be able to add services like LND hub ?
Answer: Based on research done with LN-Bank, it will be possible to add multiple services as plugins.

Final question regarding LN wallet setup is redirected to support [chat](https://chat.btcpayserver.org).
