### ISSUE TITLE
Animation Call #0

### ISSUE THREAD

**Issue by webworthy** [btcpayserver/organization#8]
```meta
Date: 2020-12-14
Time: 6:00pm
Timezone: CET
Duration: 1h
UTCTime: 2020-12-14 05:00 UTC
```

### Agenda
This could be one of many, for the first meeting I'd like to cover the following: 

1. Outline the general purpose and goal of the video
2. Make a list of what concepts we need to cover - both technical and theoretical
3. Mention any other videos or 3D art styles anyone likes that could help as a reference  
4. Review current artwork and concepts 

### Check your timezone

https://everytimezone.com/s/30665c74

### Join the call

https://meet.jit.si/BTCPayAnimationCall

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Zaxounette** [comment]
Will be there.

**Comment by pavlenex** [comment]
Meeting re-scheduled for 16th.  Re-opening so it reflects calendar changes.

**Comment by pavlenex** [comment]
Thanks everyone for joining in the first animation meeting. It was very creative and productive discussion.
I'll try to outline what we came up with instead of the notes. The idea is to have a reverse story. Usually into videos begin with problem-solution-happy ending. What we want to do here is have happy situation with an ending with a twist.

The idea is to explain btcpay server core principles and how it solves problems (no fees, privacy, no third-party, censorship resistance, etc) as the scene evolves, the idea spreads with btcpay server being a block (like a lego block) where people can add stuff on top of it and expand it (horizontally and vertically showcasing btcpay as a payment platform that's modular and extensive and allows all sorts of applications not just payment processing. As scene progresses, we zoom out and see plenty of these btcpay blocks forming a community and circular economy. The ending should show the portion of the neighbors (the world) being chaotic where as the "community" part shows happy ending.

I am very bad at narrating, so if anybody wants to better clarify stuff, feel free to, but this TLDR from today's meeting!
